export const
    SET_LOGIN = "SET_LOGIN",
    TOGGLE_SPINNER = "TOGGLE_SPINNER",
    SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO",
    SET_LIST_MUSIC = "SET_LIST_MUSIC",
    SET_FORCE_MUSIC = "SET_FORCE_MUSIC",
    SET_TITLE_LIST_MUSIC = "SET_TITLE_LIST_MUSIC",
    SET_LISTENED_MUSIC = "SET_LISTENED_MUSIC",
    SET_COMMENT = "SET_COMMENT"
